bdays:
  container_name: bdays
  tty: true
  stdin_open: true
  build: "."
  links:
    - pg
  ports:
    - 8080:8080
pg:
  image: postgres:9.6.16
  container_name: pg
  ports:
    - 5432:5432
  environment:
    - POSTGRES_DB=bdays
